### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by adamthomasgoss** [Xyene/cube2sphere#1]
Hello Xyene, thank you for providing this awesome tool. 

When trying to install (on OSX) using
`pip install cube2sphere`
I get the following error
`Could not find a version that satisfies the requirement cube2sphere (from versions: )
No matching distribution found for cube2sphere`
Is this a Python error on my end? Or something that needs to be updated in the project?
I am running Python 5.3.1 with pip 8.1.1

Thanks,
Adam

**Comment by Xyene** [comment]
Hi!

It looks like I did something wrong while uploading the project to PyPi, which is why there's no distribution found.

You can install the project directly though, with:

```
pip install -e git://github.com/Xyene/cube2sphere.git#egg=cube2sphere
```

In figuring out the error I've found that the `ez_setup` I use isn't compatible with Python 3, so you'll need a Python 2 install. I'll get the issue fixed soon, but running the command above with a Python 2 install should work for now.

**Comment by adamthomasgoss** [comment]
Hello Xyene!

Thank you for the immediate response. I switched to Python **2.7.11** and was able to install cube2sphere with no problems using the direct method you suggested above.

Again, **many** thanks,
Adam

**Comment by Xyene** [comment]
Happy to hear it worked!
